package ru.neexol.debtable.utils.exceptions.conflict

class UserAlreadyInvitedException : Exception()